In [3]:
# 학습
# Data : ALL

import tensorflow as tf
import h5py
import numpy as np
import os


In [5]:
print(os.getcwd())
print(os.listdir())

C:\Users\vivid\바탕 화면\YeloCarModel\Yelo_Car_repository
['.ipynb_checkpoints', '20220110_train.ipynb', '20220110_train_mp4.ipynb', '210110_mk_dataset_with_hsv.ipynb', '210110_mk_dataset_with_hsv_2.ipynb', '220111_mk_dataset_with_hsv_0316_mp4.ipynb', '220111_mk_dataset_with_hsv_mp4_all_data+train.ipynb', '220111_mk_dataset_with_hsv_mp4_partial_data+train.ipynb', '220112_mk_dataset_with_hsv_mp4_all_data+train.ipynb', 'Data', 'HDF5', 'Model', 'mp4Data', 'mp4Model', 'Untitled.ipynb']


## All Dataset : 'test13_all' -> Model 첫 시도 
#### Epoch 9/100 36/36 [==============================] - 22s 606ms/step - loss: 0.0038 - mae: 0.0430 - mse: 0.0038 - val_loss: 0.0037 - val_mae: 0.0476 - val_mse: 0.0037

In [6]:
model_version = 'model_20220111_all_1'

with h5py.File('./Model/Model_test13_all/dataset_hsv_test13_all.hdf5', 'r') as hf:
    image_train = np.array(hf['x_train'][:, :, :, :])
    action_train = np.array(hf['y_train'][:, :])
    image_val = np.array(hf['x_val'][:, :, :, :])
    action_val = np.array(hf['y_val'][:, :])

# print(image_train)
# print(action_train)
# print(image_val)
# print(action_val)
    
(x_train, y_train), (x_test, y_test) = (image_train, action_train), (image_val, action_val)

x_train /= 255.
x_test /= 255.

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, 3, activation='relu', input_shape=(48, 64, 3)),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(32, 3, activation='relu'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(32, 3, activation='relu'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(2)
])

optimizer = tf.keras.optimizers.RMSprop(0.001)

callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)
model.compile(loss='mse', optimizer=optimizer, metrics=['mae', 'mse'])

model.summary()
history = model.fit(x=x_train, y=y_train, batch_size=256, epochs=100, validation_data=(x_test, y_test), callbacks=[callback])

print("\n")
print(model.evaluate(x_test, y_test))


# model.save('./script/Model/'+model_version)
tf.saved_model.save(model, './Model/Model_test13_all/'+model_version)

del model

# model = tf.keras.models.load_model('./script/Model/'+model_version)
# print(model.evaluate(x_test, y_test))
# model.summary()

model = tf.saved_model.load('./Model/Model_test13_all/'+model_version)
outputs = model(x_test[0:10])

print(outputs)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 46, 62, 32)        896       
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 23, 31, 32)        0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 21, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 10, 14, 32)        0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 8, 12, 32)         9248      
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 4, 6, 32)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 768)              

## All Dataset : 'test14_20220112_all'
#### Epoch 25/100 12/12 [==============================] - 6s 536ms/step  loss: 0.0025 - mae: 0.0347 - mse: 0.0025 - val_loss: 0.0024 - val_mae: 0.0383 - val_mse: 0.0024

In [5]:
model_version = 'model_20220112_all_2'
dataset_version = 'test14_20220112_all'

with h5py.File('./Model/Model_' + dataset_version + '/dataset_hsv_' + dataset_version + '.hdf5', 'r') as hf:
    image_train = np.array(hf['x_train'][:, :, :, :])
    action_train = np.array(hf['y_train'][:, :])
    image_val = np.array(hf['x_val'][:, :, :, :])
    action_val = np.array(hf['y_val'][:, :])

# print(image_train)
# print(action_train)
# print(image_val)
# print(action_val)
    
(x_train, y_train), (x_test, y_test) = (image_train, action_train), (image_val, action_val)

x_train /= 255.
x_test /= 255.

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, 3, activation='relu', input_shape=(48, 64, 3)),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(32, 3, activation='relu'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(32, 3, activation='relu'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(2)
])

optimizer = tf.keras.optimizers.RMSprop(0.001)

callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)
model.compile(loss='mse', optimizer=optimizer, metrics=['mae', 'mse'])

model.summary()
history = model.fit(x=x_train, y=y_train, batch_size=256, epochs=100, validation_data=(x_test, y_test), callbacks=[callback])

print("\n")
print(model.evaluate(x_test, y_test))


# model.save('./script/Model/'+model_version)
tf.saved_model.save(model, './Model/Model_' + dataset_version + '/' + model_version)

del model

# model = tf.keras.models.load_model('./script/Model/'+model_version)
# print(model.evaluate(x_test, y_test))
# model.summary()

model = tf.saved_model.load('./Model/Model_' + dataset_version + '/' +model_version)
outputs = model(x_test[0:10])

print(outputs)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 46, 62, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 23, 31, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 21, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 10, 14, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 8, 12, 32)         9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 4, 6, 32)          0         
_________________________________________________________________
flatten (Flatten)            (None, 768)               0

In [5]:
model_version = 'model_20220112_all_2'
dataset_version = 'test14_20220112_all'

with h5py.File('./Model/Model_' + dataset_version + '/dataset_hsv_' + dataset_version + '.hdf5', 'r') as hf:
    image_train = np.array(hf['x_train'][:, :, :, :])
    action_train = np.array(hf['y_train'][:, :])
    image_val = np.array(hf['x_val'][:, :, :, :])
    action_val = np.array(hf['y_val'][:, :])

# print(image_train)
# print(action_train)
# print(image_val)
# print(action_val)
    
(x_train, y_train), (x_test, y_test) = (image_train, action_train), (image_val, action_val)

x_train /= 255.
x_test /= 255.

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, 3, activation='relu', input_shape=(48, 64, 3)),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(32, 3, activation='relu'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Conv2D(32, 3, activation='relu'),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(2)
])

optimizer = tf.keras.optimizers.RMSprop(0.001)

callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3)
model.compile(loss='mse', optimizer=optimizer, metrics=['mae', 'mse'])

model.summary()
history = model.fit(x=x_train, y=y_train, batch_size=256, epochs=100, validation_data=(x_test, y_test), callbacks=[callback])

print("\n")
print(model.evaluate(x_test, y_test))


# model.save('./script/Model/'+model_version)
tf.saved_model.save(model, './Model/Model_' + dataset_version + '/' + model_version)

del model

# model = tf.keras.models.load_model('./script/Model/'+model_version)
# print(model.evaluate(x_test, y_test))
# model.summary()

model = tf.saved_model.load('./Model/Model_' + dataset_version + '/' +model_version)
outputs = model(x_test[0:10])

print(outputs)

print(x_test[0:10])

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 46, 62, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 23, 31, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 21, 29, 32)        9248      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 10, 14, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 8, 12, 32)         9248      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 4, 6, 32)          0         
_________________________________________________________________
flatten (Flatten)            (None, 768)               0

In [21]:
from PIL import Image
import cv2
#cv2.imwrite('filename.jpeg', x_test[727])
np.set_printoptions(threshold=np.inf, linewidth=np.inf)

#type(x_test[0])
x_test /= 255
x_test /= 255

print(x_test[0])
cv2.imwrite('filename.jpeg', x_test[0])



[[[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.

True